### ISSUE TITLE
Build Tools Doc Update 

### ISSUE THREAD

**Issue by AntoninSlejska** [pantheon-systems/documentation#3633]
Re: [Build Tools](https://pantheon.io/docs/guides/build-tools/create-project/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:

The Website could not be created. After the command

`terminus build:project:create d8 composer-d8site-antonin`

the following error message is displayed:

```
...

 [notice] Running git -C C:\Users\Slejska\AppData\Local\Temp\locE3F0.tmp/composer-d8site-antonin commit -m 'Initial commit'
error: pathspec 'commit'' did not match any file(s) known to git.
 [error]  Command `git -C C:\Users\Slejska\AppData\Local\Temp\locE3F0.tmp/composer-d8site-antonin commit -m 'Initial commit'` failed with exit code 1
PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove file "C:\Users\Slejska\AppData\Local\Temp\locE3F0.tmp\composer-d8site-antonin\.git\objects\f6\bcce203b03ad135ad2d9e4a572c3d064246fa4": unlink(C:\Users\Slejska\AppData\Local\Temp\locE3F0.tmp\composer-d8site-antonin\.git\objects\f6\bcce203b03ad135ad2d9e4a572c3d064246fa4): Permission denied. in C:\Workspace\terminus\vendor\symfony\filesystem\Filesystem.php:186
Stack trace:
#0 C:\Workspace\terminus\vendor\symfony\filesystem\Filesystem.php(178): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 C:\Workspace\terminus\vendor\symfony\filesystem\Filesystem.php(178): Symfony\Component\Filesystem\Filesystem->remove(Array)
#2 C:\Workspace\terminus\vendor\symfony\filesystem\Filesystem.php(178): Symfony\Component\Filesystem\Filesystem->remove(Array)
#3 C:\Workspace\terminus\vendor\symfony\filesystem\Filesystem.php(178): Symfony\Component\Filesystem\Filesystem->remove(Array)
#4 C:\Workspace\terminus\vendor\symfony\filesystem\Filesystem.php in C:\Workspace\terminus\vendor\symfony\filesystem\Filesystem.php on line 186
PHP Stack trace:
PHP   1. {main}() C:\Workspace\terminus\vendor\pantheon-systems\terminus\bin\terminus:0

Fatal error: Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove file "C:\Users\Slejska\AppData\Local\Temp\locE3F0.tmp\composer-d8site-antonin\.git\objects\f6\bcce203b03ad135ad2d9e4a572c3d064246fa4": unlink(C:\Users\Slejska\AppData\Local\Temp\locE3F0.tmp\composer-d8site-antonin\.git\objects\f6\bcce203b03ad135ad2d9e4a572c3d064246fa4): Permission denied. in C:\Workspace\terminus\vendor\symfony\filesystem\Filesystem.php on line 186
```

## terminus self:info

```
  PHP binary                C:\xampp\php\php.exe
  PHP version               7.2.2
  php.ini used              C:\xampp\php\php.ini
  Terminus project config
  Terminus root dir         C:\Workspace\terminus\vendor\pantheon-systems\terminus
  Terminus version          1.8.0
  Operating system          build 16299 (Windows 10)
```

**Comment by alexfornuto** [comment]
@AntoninSlejska Thanks for reporting! Do you have the [Build Tools Plugin](https://github.com/pantheon-systems/terminus-build-tools-plugin) installed?

**Comment by AntoninSlejska** [comment]
@alexfornuto Thanks! I have installed:

 * Terminus Composer Plugin
 * Terminus Drupal Console Plugin
 * Terminus Build Tools Plugin

**Comment by alexfornuto** [comment]
@AntoninSlejska Thanks for the additional information. I've alerted the Terminus team to this issue, and in the meantime I'm setting up a Windows VM to try and replicate.

**Comment by alexfornuto** [comment]
@AntoninSlejska Are you using Bash for Windows? If not, could you give that a try?
