### ISSUE TITLE
Disable REST API and Require JWT / OAuth Authentication

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#4478]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues/)

Priority: Low

## Issue Description:
Ticket: 126029
The plugin "Disable REST API and Require JWT / OAuth Authentication" causes WP CLI to fail, specifically along with Woocommerce due to it blocking related functions

```Fatal error: Uncaught Error: Call to undefined method WP_Error::get_data() in /srv/bindings/c5107ba402534a44a732d24c641a8106/code/wp-content/plugins/woocommerce/includes/cli/class-wc-cli-runner.php:64
Stack trace:
#0 phar:///opt/pantheon/wp-cli1/wp-cli.phar/php/class-wp-cli.php(273): WC_CLI_Runner::after_wp_load()
#1 phar:///opt/pantheon/wp-cli1/wp-cli.phar/php/WP_CLI/Runner.php(1199): WP_CLI::do_hook('after_wp_load')
#2 phar:///opt/pantheon/wp-cli1/wp-cli.phar/php/WP_CLI/Runner.php(1100): WP_CLI\Runner->load_wordpress()
#3 phar:///opt/pantheon/wp-cli1/wp-cli.phar/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#4 phar:///opt/pantheon/wp-cli1/wp-cli.phar/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#5 phar:///opt/pantheon/wp-cli1/wp-cli.phar/php/wp-cli.php(23): WP_CLI\bootstrap()
#6 phar:///opt/pantheon/wp-cli1/wp-cli.phar/php/boot-phar.php(8): include('phar:///opt/pan...')
#7 /opt/pantheon/wp-cli1/wp-cli.phar(4): include('phar:///opt/pan...')
#8  in /srv/bindings/c5107ba402534a44a732d24c641a8106/code/wp-content/plugins/woocommerce/includes/cli/class-wc-cli-runner.php on line 64
```

## Suggested Resolution

Disable plugin, provide alternative methods to disable REST or similar objectives

**Comment by alexfornuto** [comment]
@eabquina what alternate methods?

**Comment by eabquina** [comment]
@alexfornuto This will need to modify the plugin to exclude WP CLI requests so it can work. Add PR #4599
